[package]
org = "aneesha"
name = "slack_numbermentioned_message_to_twilio"
version = "0.1.0"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "twilio"
version = "0.99.5"

[[dependency]]
org = "ballerinax"
name = "slack"
version = "0.9.6"